TODO.md, dockerfiles/base/Dockerfile, mltsp/Flask/flask_app.py, mltsp/TCP/tests/test_feature_generation.py, mltsp/build_model.py, mltsp/cfg.py, mltsp/custom_feature_tools.py, mltsp/docker_scripts/docker_build_model.py, mltsp/docker_scripts/docker_extract_custom_feats.py, mltsp/docker_scripts/docker_featurize.py, mltsp/docker_scripts/docker_predict.py, mltsp/docker_scripts/run_disco_tst.py, mltsp/ext/flask_googleauth.py, mltsp/featurize.py, mltsp/lc_tools.py, mltsp/parallel_processing.py, mltsp/predict_class.py, mltsp/run_in_docker_container.py, mltsp/tests/Data/asas_training_subset_classes.dat, mltsp/tests/test_build_model.py, mltsp/tests/test_custom_feats.py, mltsp/tests/test_featurize.py, mltsp/tests/test_flask_app.py, mltsp/tests/test_parallel_processing.py, mltsp/tests/test_predict.py, mltsp/tests/test_run_in_docker_container.py, run_script_in_container.py
Fixed syntax error in TCP test script.
Incorporated TCP feature generation into main test suite.
Changed npt.assert_equal to npt.assert_almost_equal for float comparisons.
=> Improved unit tests.

mltsp/Flask/flask_app.py, mltsp/parallel_processing.py, mltsp/tests/test_parallel_processing.py
@acrellin I hope this will take care of most of your problems.
The one error seems to be due to a missing config file?  Not sure what's happening there.
=> Fix errors introduced during casperjs merge

TODO.md, mltsp/disco_tools.py, mltsp/docker_scripts/docker_featurize.py, mltsp/featurize.py, mltsp/parallel_processing.py, mltsp/predict_class.py, mltsp/tests/test_featurize.py, mltsp/tests/test_parallel_processing.py, mltsp/tests/test_predict.py, mltsp/tests/test_run_in_docker_container.py
=> DDFS integration

Makefile, mltsp/TCP/Software/feature_extract/Code/extractors/common_functions/_eigs.h, mltsp/TCP/Software/feature_extract/Code/extractors/common_functions/_lomb_scargle.h
@bnaul Can you please check whether this fixes your problem?
=> Change inline functions to static

requirements.txt
Noticed this was missing when I was setting up my local app.
=> Added waitress to requirements

.drone/build.sh, .gitignore, MANIFEST.in, Makefile, doc/install.md, mltsp/Flask/flask_app.py, mltsp/__init__.py, mltsp/cfg.py, mltsp/mltsp.yaml.example, mltsp/setup.py, mltsp/version.py, requirements.txt, setup.py
@bnaul Please do a quick check for me before I tag 0.3.
=> Prepare release

.drone/build.sh, Makefile, doc/Makefile, doc/conf.py, doc/index.rst, doc/install.md, doc/tools/apigen.py, doc/tools/build_api_docs.py, dockerfiles/base/Dockerfile, dockerfiles/drone/Dockerfile, mltsp/Flask/flask_app.py, mltsp/predict.py, mltsp/tests/test_custom_feats.py, mltsp/tests/test_flask_app.py, mltsp/util.py, requirements.txt
- Auto-generate API docs with `make api`
- Simplify installation docs (incl. separating backend and frontend)
- Slightly simplify requirements: remove `simplejson`, `nose{-,exclude}`
Still to do, but not for this PR I think:
- Make a pretty landing page w/ a basic overview
- Add examples
=> Documentation improvements

mltsp/Flask/flask_app.py, mltsp/Flask/templates/index.html, mltsp/build_model.py, mltsp/ext/sklearn_models.py, mltsp/tests/test_build_model.py, mltsp/tests/test_flask_app.py, mltsp/tests/test_predict.py, mltsp/tests/test_util.py, mltsp/util.py, requirements.txt
E.g. `RFC` becomes `Random Forest Classifier`
=> Rename models (#101); improve type casting; add unit tests; update requirements.txt

.drone/build.sh, doc/conf.py, doc/tools/build_api_docs.py
Hopefully will result in a complete API doc being autogenerated on readthedocs.
=> Add additional mock requirements for autodoc build

doc/conf.py, requirements.readthedocs.txt
Reverts mltsp/mltsp#129: I was confused and they actually omitted that fix from the new release (I was testing the wrong verison); fingers crossed for sphinx 1.3.5...
=> Revert "Undo hacky porterstemmer/sphinx fix from #126"

dockerfiles/drone/Dockerfile
@acrellin @bnaul Mergin this to get nginx into the drone image
=> Install nginx in drone Docker image

dockerfiles/drone/Dockerfile, requirements.txt
Also add HDF5, netCDF4 headers to Drone dockerfile
=> Add netCDF4 requirement

cesium/featurize.py, cesium/tests/test_featurize.py
This should have been in the previous PR, just a small simplification made possible by the elimination of `celery_tasks.py`.
=> Remove featurize_tools.py

.drone/travis_script.sh
This pull request should not trigger an update, but merging it should (fingers crossed).
=> Re-enable auto-deploy of docs

cesium/build_model.py, cesium/tests/fixtures.py, cesium/tests/test_build_model.py, cesium/tests/test_predict.py
Fixes #92. Combined with cesium-ml/cesium_web#109 this should also make debugging failures on the frontend easier.
=> Raise more detailed exception when encountering invalid feature values

cesium/featureset.py, cesium/featurize.py, cesium/tests/fixtures.py, cesium/tests/test_featureset.py
- Implements imputation (constant value + mean/median/mode)
- Overloads indexing to simplify extracting features for specific time series
=> Add Featureset class extending xr.Dataset

cesium/build_model.py, cesium/predict.py, cesium/tests/test_build_model.py
Updated `sklearn.grid_search` to `sklearn.model_selection` as per #138. Underlying code does not appear to need much changing, but please let me and @alejandrogarciasalas know if this breaks anything.
=> Model selection

cesium/features/cadence_features.py
Fixes #217. Nice catch @arkwave.
=> Fix array indexing bug in double_to_single_step

cesium/features/cadence_features.py, cesium/features/tests/test_cadence_features.py, cesium/tests/test_transformation.py
Added in tests for test_cadence_features and test_transformation.py.
- coverage for cadence_features up to 92% from 78%
- coverage for transformation.py up top 83% from 68%
Added in line in cadence_features.py to account for python lists incorrectly being passed in as input.
=> Testcoverage

cesium/featureset.py, cesium/featurize.py, cesium/tests/fixtures.py
Fixes test failures introduced by breaking changes in xarray 0.9.0 API.
=> Explicitly assign channel coordinate for compatibility w/ new xarray (0.9+)

cesium/featureset.py, cesium/featurize.py, cesium/tests/fixtures.py, cesium/tests/test_featureset.py, cesium/time_series.py
- Change "label" to "name" to avoid confusion w/ class labels
- Fix indexing so that `fset[inds]` works if `inds` are `numpy` ints (not just `int` ints)
=> `Featureset` API tweaks

.gitignore, .travis/travis_install.sh, .travis/travis_script.sh, Makefile, cesium/datasets/tests/test_datasets.py, cesium/tests/test_data_management.py, cesium/tests/test_featureset.py, cesium/tests/test_featurize.py, cesium/tests/test_predict.py, cesium/tests/test_time_series.py, cesium/tests/test_transformation.py, cesium/tests/test_util.py, doc/install.md
I ported all test to use pytest instead of nose. I tried to use the equivalent functions in pytest without changing the structure of the tests. Also updated Travis build to use pytest. 
All tests pass locally with pytest and nose uninstalled. Travis build passes.
=> Port nose to pytest (fixes #242)

cesium/featurize.py, cesium/tests/fixtures.py, cesium/tests/test_featurize.py
* Make `save_featureset` and `load_featureset` handle data frames
* Return labels in `featurize_ts_files`
=> Featurize API tweaks

cesium/featurize.py, cesium/tests/test_featurize.py
@aricq wanna take a look and make sure this behaves like you wanted?
=> Add flag for suppressing exceptions during featurization

README.md
This would have saved me quite a bit of time :)
=> Add note regarding MSVC

doc/tools/apigen.py
The goal of this PR is to make the code more Pythonic by utilizing Python with statements.
=> [Refactoring] making the code more Pythonic

cesium/features/lomb_scargle.py, cesium/features/tests/test_lomb_scargle_features.py
added two new key/values based on the original L-S refine script.
=> added bookkeeping to the results dictionary

CONTRIBUTING.md
pull in overall contribution guidelines from SkyPortal.
=> contributing update

.github/workflows/docs_build.yml, CONTRIBUTING.md, cesium/features/cadence_features.py, cesium/features/common_functions.py, cesium/features/graphs.py, cesium/features/tests/test_cadence_features.py, doc/conf.py, requirements.txt
I extended cadence_features.py, with two new functions: compute_time_lag_stats and compute_time_lag_skew_kurtosis. The compute_time_lag_stats function calculates the mean and standard deviation of the time lags, while the compute_time_lag_skew_kurtosis function computes the skewness and kurtosis. The additions offer support for time lag distributions, offering insights into their central tendency, dispersion, and shape.
=> Time lag stats

cesium/features/cadence_features.py
Remove cadence calculation functions left over from previous commit.
=> remove unneeded functions

.git-blame-ignore-revs, .gitignore, .pre-commit-config.yaml, cesium/data_management.py, cesium/datasets/andrzejak.py, cesium/datasets/asas_training.py, cesium/datasets/tests/test_datasets.py, cesium/features/period_folding.py, cesium/features/tests/test_general_features.py, cesium/features/tests/test_lomb_scargle_features.py, cesium/tests/fixtures.py, cesium/tests/test_featurize.py, cesium/time_series.py, doc/conf.py, doc/tools/apigen.py, pyproject.toml, tools/check_sdist.py
=> Flake8 to ruff
