MANIFEST.in
doc/install.md
mltsp/Flask/flask_app.py
mltsp/__init__.py
mltsp/cfg.py

Users can now get up and running with:
``import mltsp; mltsp.install()``
May have to work around authentication requirements still in another PR.

Simplify configuration stage

---

mltsp/TCP/Software/feature_extract/Code/generators_importers/from_xml.py

`type('')==bytes` evaluates to `True` in Python2, and `False` in Python3. This
was causing some variable to never be set, which eventually led to
various silent errors downstream; the ultimate result was the
uncertainty values not being properly loaded from the data, which caused
all features which used those to have the wrong values.

Fix bug causing feature test failures in Python3

---

mltsp/Flask/flask_app.py
mltsp/Flask/static/js/scripts.js
mltsp/Flask/templates/index.html
mltsp/custom_feature_tools.py
mltsp/featurize.py
mltsp/run_script_in_container.py
mltsp/tests/test_featurize.py
mltsp/tests/test_flask_app.py

Have to do a `sys.path.append` for the import to work now, which is why the script was originally placed where it was, though it's only run inside a Docker container so I think it's fine to do so.

Move run_script_in_container into mltsp sub-directory (fixes #80)

---

mltsp/build_model.py
mltsp/cfg.py
mltsp/featurize.py
mltsp/featurize_tools.py
mltsp/predict.py
mltsp/science_features/periodic_model.py
mltsp/tests/test_featurize.py

- Allow unequal-length multichannel data (passed in as lists of lists of 1d arrays), e.g. in the case of wavelet-transformed data
- Add support for directly passing custom features as a dict `{'some_feature': f}` where `f(t,m,e)` is a featurization function, or as a dask graph `{'some_feature': (f, 't', 'm', 'e')}`.
- Use default values for times/errors when omitted from `featurize_time_series`

Featurization API tweaks

---

mltsp/build_model.py
mltsp/featurize.py
mltsp/predict.py

Small (bug?)fix: the main work of `rectangularize_featureset` is done by the Pandas `unstack` function, which automatically sorts the dataframe (by row); this leads to unexpected behavior when e.g. checking model predictions against a list of known targets. This change explicitly undoes any sorting and preserves the original ordering of `featureset.name`, which I think is how one would expect it to work.

Fix rectangularizing featureset w/ unsorted labels

---

Makefile
mltsp/featurize_tools.py
mltsp/obs_feature_tools.py
mltsp/tests/test_featurize.py
mltsp/tests/test_flask_app.py
mltsp/tests/test_predict.py

This should fix all the remaining Python3 incompatibilities (which were almost all problems with the test code and how data read from files/web requests were being compared to known string values).
Fixes #75.

Python3 fixes: str encodings, iterator usage

---

mltsp/predict.py
mltsp/science_features/new_ls.py

Add functionality to `build_model.model_predictions` to always return labels instead of probabilities if desired; avoid inconvenience of needing to coerce probabilities into labels when labels are all that are desired.
Re-opening #112 with only the relevant commit. Docstring now says "only the top predicted label for each time series is returned".

Add parameter to control prediction type

---

.drone/build.sh
Makefile
dockerfiles/drone/Dockerfile
requirements.readthedocs.txt

Add missing `numpydoc` package to `requirements.readthedocs.txt`. Also add a Makefile target `make html` which compiles the docs (as in scikit-image), and have Drone test the docs build.
EDIT: Also fixes the broken front-end tests on Drone, once that Docker image is rebuilt.
EDIT EDIT: Fixes #37!

Add missing docs requirement, build docs on Drone

---

doc/conf.py
mltsp/science_features/amplitude.py

Some libraries were already present on Drone (e.g. `requests`) and not readthedocs; from now on Drone should fail whenever readthedocs is missing a dependency or mock library.
Also fixes a docstring indentation warning.

Mock out additional readthedocs libraries

---

doc/conf.py

`__import__` trickery makes blocks like this not work correctly (from `sphinx.search.en`):
```
try:
from porterstemmer import Stemmer as CStemmer
CSTEMMER = True
PYSTEMMER = False
except ImportError:
CSTEMMER = False
try:
from Stemmer import Stemmer as PyStemmer
PYSTEMMER = True
except ImportError:
from sphinx.util.stemmer import PorterStemmer
PYSTEMMER = False
```
I added a special case for this which seems to have fixed it; this is the price of trying to auto-mock dependencies, I guess...

Fix doc build by properly failing to import porterstemmer

---

doc/conf.py
requirements.readthedocs.txt

New version of sphinx (1.3.4) fixes the relevant bug (https://github.com/sphinx-doc/sphinx/issues/2183), so this undoes the patch from #126 and bumps the required sphinx version for readthedocs.

Undo hacky porterstemmer/sphinx fix from #126

---

doc/conf.py

Something about the internal imports of `pandas` caused our way of using `MagicMock` to be very slow; this fix causes mock libraries to be returned only for simple import errors, whereas other types of errors within `__import__` will just be ignored.
Old doc build:
`make html  106.99s user ... 1:50.61 total`
New doc build:
`make html  5.39s user ... 5.845 total`

Speed up import mocking in API doc generation

---

Makefile
doc/conf.py
requirements.readthedocs.txt

Tried this in #129 but the relevant `sphinx` change didn't get actually released in that minor version update; this time it's there for real.

(re-)Undo hacky porterstemmer/sphinx fix from #126

---

requirements.txt

Old version wouldn't work on Linux under Python3 due to packaging problem, fixed in `stormpath==2.1.9`.

Replace git install of `stormpath` with new non-broken PyPI version

---

tools/casper_install.sh

[casperjs](https://github.com/n1k0/casperjs) is now under the `casperjs` organization instead of `n1k0` so the source is extracted to a different path.

Fix casper install bug caused by remote repo rename

---

Makefile
doc/Makefile
doc/_static/output_cells.css
doc/conf.py
doc/index.rst
examples/README.txt
examples/plot_EEG_Example.py
requirements.docs.txt

Should make using `doctr` easier since everything will be executed by `sphinx` instead of via a separate external pipeline (see https://github.com/cesium-ml/cesium/pull/216).

Use `sphinx_gallery` instead of markdown for examples

---

cesium/__init__.py
cesium/features/cadence_features.py
cesium/features/graphs.py
cesium/features/tests/test_cadence_features.py

26,244x faster for `n=41442`:
Old:
```
%time cf.delta_t_hist(t)
Wall time: 1min 56s
```
New:
```
%time cf.delta_t_hist(t)
Wall time: 4.42 ms
```

Optimize `delta_t_hist` using convolutions

---

.drone/travis_install.sh

This is a requirement for nose to generate a coverage report, subsequently
uploaded to codecov.

Do pip install of coverage during travis-ci run

---

.drone/deploy_docs.sh

It looks like these checks were removed with the transition to doctr.  It did
not cause any problems, because the various branches do not have the tokens
required to push.  Still, for safety, add a check to ensure deploying only
from the master branch, and not from a PR.

Only deploy docs when on master

---

cesium/features/_eigs.h

From my limited understanding of C99 inline this is required, as no
`extern inline` is done for those symbols anywhere.

Make SQR and SIGN static inline.

---

cesium/featurize.py

When reading a CSV into a pandas DataFrame (`pd.read_csv`), empty channel values are filled with a string ("Unnamed ...") which, when saved and then loaded with `load_featureset`, breaks the type-casting of channel values from string to int, unless empty. This changes the check from whether it's empty to whether it's a digit, to handle the above-specified case.

Update load_featureset to handle filler strings for empty channel values

---

cesium/featurize.py
requirements.txt

Related to https://github.com/cesium-ml/cesium/pull/276 https://github.com/cesium-ml/cesium/issues/277.
I think this is the only places where `get` was used. I updated the `requirements.txt`.

Compatibility with dask 0.20 : 'get' keyword replaced with 'scheduler'

---

cesium/util.py

Exclude files starting with '.' and '/' from being extracted from tarball/zipfile

---

README.md

This PR makes it more explicit that Windows installation requires installing from source, as we don't build Windows binary wheels.

Update README.md Windows installation instructions

---

.flake8
.pre-commit-config.yaml
cesium/time_series.py

For Python 3.10 compatibility, "from collections import Iterable" should be changed into "from collections.abc import Iterable".
See for example:
https://stackoverflow.com/questions/72032032/importerror-cannot-import-name-iterable-from-collections-in-python

Change "collections" into "collections.abc" for Python 3.10 compatibility

---

requirements.txt

Longer term solution:
(1) Find out if the pandas change was intentional (see https://github.com/pandas-dev/pandas/issues/52712)
(2) If so, do an audit of `.values` assignments, and re-release with pin removed
Closes #318

The test suite fails with pandas 2.0; pin to <2

---

SECURITY.md

Tidelift donates to Scientific Python to allow for continued maintenance of this package.
One of their requirements is to have a security contact.

Document how to report security issues
